@startuml OOP_Homework7_UseCaseDiagram
left to right direction
 
actor user as "一般使用者"
actor computer as "電腦計時器"

rectangle MyBackup {
	user -- (設定處理目標)
	user -- (設定處理時程)
	user -- (設定處理方式)
	user -- (執行處理工作)
	computer -- (執行處理工作)
	computer -- (自動排程工作)
}

@enduml